### ISSUE TITLE
Skeleton Frames

### ISSUE THREAD

**Issue by codewithkyle** [codewithkyle/brixi-components#17]
Create a skeleton frame class:

```scss
.skeleton{
    display: block;
    position: relative;
    border-radius: 0.25rem;
    overflow: hidden;
    background-color: var(--grey-200);

    &.-image{
        &::before{
            content: "";
            display: block;
            width: 100%;
            padding-bottom: 75%;
        }
    }

    &.-heading{
        height: 36px;
    }

    &.-copy{
        height: 24px;
    }

    &.-button{
        height: 36px;
        width: 96px;
    }

    &::after{
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: linear-gradient(to right, transparent, var(--grey-300), transparent);
        animation: skeleton 900ms linear infinite;
    }
}
@keyframes skeleton{
    from{
        transform: translateX(-200%);
    }
    to{
        transform: translateX(100%);
    }
}
```
